services:
  server:
    build: .
    develop:
      watch:
        - action: restart
          path: ./config/mods
    image: ghcr.io/sunketchupm/sm64coopdx-server:latest
    tty: true
    volumes:
      - ./baserom.us.z64:/sm64/baserom.us.z64:ro
      - ./config:/sm64/config
    command: [
      "./sm64coopdx",
      "--savepath", "!/config",
      "--headless",
      "--skip-update-check"
    ]
    user: "1000:1000"
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
