services:
  server:
    build: .

    develop:
      watch:
        - action: restart
          path: ./config/mods

    logging:
      driver: "json-file"
      options:
        max-size: "1000m"
        max-file: "10"

    user: "1000:1000"
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tty: true

    image: ghcr.io/sunketchupm/sm64coopdx-server:latest
    volumes:
      - ./baserom.us.z64:/sm64/baserom.us.z64:ro
      - ./config:/sm64/config
    command: [
      "./sm64coopdx",
      "--savepath", "!/config",
      "--headless",
      "--skip-update-check",
      # Leave blank to make a public lobby, or set a password to make a private lobby
      "--coopnet", ""
    ]
